### ISSUE TITLE
Infinity SPI values

### ISSUE THREAD

**Issue by oliverangelil** [sbegueria/SPEI#11] opened 2017-05-12 02:29 UTC
I've calculated SPI at every grid cell using monthly rainfall in all of the [CMIP5 models](https://en.wikipedia.org/wiki/Coupled_model_intercomparison_project), for scale=3 and scale=6, using a Gamma distribution and a rectangular window type. It seems that infinity SPI values result in rare occasions when the 3 or 6 precip values are zero or extremely close to zero (I'm seeing this over the Sahara for example). The higher the scale, the fewer infinity values result. Perhaps in these cases, the SPI should be artificially set to -2, or to NaN?

**Comment by sbegueria** [comment] 2017-05-12 07:12
Hi, yes in some ocasions it is not possible to compute the index. That's one of the reasons for us to do not compute the SPI/SPEI over deserts.

You can try using a PearsonIII distrib also ib the package, it is more flexible and produces less NaNs.

Santiago Beguería

**Comment by solhailu** [comment] 2017-09-07 08:05
Dear Oliverangelil and Sbegueria,
I am trying to compute the SPI for monthly rainfall data avalibale in netcdf format (.nc). is there any code or extension avalibel to compute for a grid cell, same as Oliverangelil did. Please kindly share the code if possible. 

Best regards,

Solomon

**Comment by sbegueria** [comment] 2017-09-07 10:49
Hi @solhailu, have a look here: https://github.com/sbegueria/SPEIbase.

**Comment by phyvera** [comment] 2022-12-24 07:10
Is anyone find solution about that infinity SPEI values? I am calculating global SPEI by using CESM-LE data and got infinite value (-Inf or -Inf).  I already consider na.rm =TRUE even if I don't have ant missing value with my data. 
Should I replace the -Inf to -3 and Inf to 3. Does it make sense? 

I already computed SPEI ( PET with THornthwaite, Hargreave and Penman) by taking different distribution such as Logistic, Gamma, PearsonIII, but I still got those Infinite and NaN values.

Any help and advice are welcome.

**Comment by sbegueria** [comment] 2022-12-24 15:51
As explained, sometimes there is no solution to the distribution fitting problem and the SPEI / SPI yields NaN or Inf. The problem is not in the code, but in the data. Sometimes the data does not conform to the distribution. Maybe there are too few data, the data consists of mostly zeros, or other weird issues. This is not a code bug, so I close the issue.

**Closed by sbegueria** 2022-12-24 15:52 UTC

**Comment by tianyang0611** [comment] 2025-01-10 19:57
> Has anyone found a solution to this problem of infinite SPEI values? I calculate the global SPEI using CESM-LE data and get an infinite value (-Inf or -Inf). I already consider na.rm =TRUE even though I have no missing value in my data. Should I replace -Inf with -3 and Inf with 3, does this make sense?
> 
> I have already calculated SPEI ( PET with THornthwaite, Hargreave and Penman) taking different distributions such as Logistic, Gamma, PearsonIII, but I still have these values Infinite and NaN.
> 
> Any help and advice is welcome

Did you solve this problem? I also occur it.

**Comment by sbegueria** [comment] 2025-01-10 20:51
As explained, this is not a coding problem, but data related. Sometimes there is no solution to the distribution fitting problem, and the SPEI / SPI yields NaN or Inf. Simply put, sometimes the data does not conform to the distribution. Maybe there are too few data, the data consists of mostly zeros, or other weird issues.
